name: Build and Deploy
on:
  push:
    branches:
      - release
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: docs/.vuepress/dist/
        BUILD_SCRIPT: yarn && yarn docs:build
